# Generated by Django 2.0.7 on 2018-07-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('display_pic', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
