# Generated by Django 2.0.7 on 2018-07-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='resume',
            field=models.FileField(default=1, upload_to='resume/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='summary',
            field=models.TextField(max_length=200),
        ),
    ]
